---
title: "Research"
---

My research studies how social interactions affect individual and aggregated economic performance. 

## Publications
* [Spectral estimation of large stochastic blockmodels with discrete nodal covariates](files/grdpg_march2021.pdf), December 2023 (with [Lingxin Hao](https://soc.jhu.edu/directory/lingxin-hao), [Joshua Cape](https://jcape1.github.io) and [Carey Priebe](https://www.ams.jhu.edu/~priebe/)), *Journal of Business and Economic Statistics* 41(4), pp 1364-1376
<!-- + Old versions: [August 2019](files/grdpg_august2019.pdf) -->
   + [grdpg](https://github.com/meleangelo/grdpg): R package to implement spectral methods for SBMs     
&nbsp;   

* [A model of inter-organizational network formation](https://www.sciencedirect.com/science/article/abs/pii/S0167268123002615) (with [Shweta Gaonkar](http://shwetagaonkar.com)), October 2023,   *Journal of Economic Behavior and Organization* 214: 82-104
<!--    + Old versions: [may 2023](files/firmnetworks_ergm_may2023.pdf) [sept 2020](files/firmnetworks_ergm_sept2020.pdf) [Dec 2018](files/firmnetworks_ergm_dec2018.pdf) -->
    + [Example of code](files/OnlineAppendix.pdf) and [data](files/data.RData): files to explain the estimation and counterfactual simulations in the paper. Data are fake (we cannot share the original data).    
&nbsp;

* [Homophily and Community Structure at Scale: An Application to a Large Professional Network](files/PP-Article.pdf), May 2023 (with Juan Nelson Martinez Dahbura, Shota Komatsu and Takanori Nishida),  *AEA Papers and Proceedings 2023*&nbsp;

* [Approximate Variational Estimation for a Model of Network Formation](https://direct.mit.edu/rest/article-abstract/105/1/113/98191/Approximate-Variational-Estimation-for-a-Model-of?redirectedFrom=fulltext), Jan 2023, *Review of Economics and Statistics*  105 (1): 113–124 (with [Lingjiong Zhu](http://www.math.fsu.edu/People/faculty.php?id=1472) )
     + [`mfergm`](https://github.com/meleangelo/mfergm): Replication package	on Github
<!--     + Old versions: [Accepted Version: May 2020](files/MeleZhuMay2020.pdf)  [March 2019](files/MeleZhuMarch2019.pdf) [Sept 2017](files/MeleZhuSeptember2017.pdf) [February 2017](files/MeleZhuFeb2017.pdf) [June 2015](http://networks.seas.harvard.edu/papers/mele_zhu.pdf)  [Arxiv](https://arxiv.org/abs/1702.00308)   -->      
     &nbsp;
      

   
* [On spectral algorithms for community detection in
stochastic blockmodel graphs with vertex covariates](https://arxiv.org/abs/2007.02156), May 2022, *IEEE Transactions of Network Science and Engineering*, volume 9, issue 5, pp. 3373 - 3384 ([journal link](https://ieeexplore.ieee.org/document/9782588))  (with Cong Mu, Avanti Athreya, [Lingxin Hao](https://soc.jhu.edu/directory/lingxin-hao), [Joshua Cape](https://jcape1.github.io) and [Carey Priebe](https://www.ams.jhu.edu/~priebe/))
&nbsp;

* [A Structural Model of Homophily and Clustering in Social Networks](files/homophily_dec2019_revisionJBES.pdf), (June 2022), *Journal of Business and Economic Statistics*, vol. 40, issue 3, pages 1377-1389 ([journal version](https://www.tandfonline.com/doi/abs/10.1080/07350015.2021.1930013))
<!--     + Old versions: [Dec 2018](files/homophily_dec2018.pdf) [Sept 2017](files/homophily_sept2017.pdf)    -->
&nbsp;    

* [Does school desegregation promote diverse interactions? An equilibrium model of segregation within schools](files/segnet_revisionAEJ.pdf), May 2020, *American Economic Journal: Economic Policy*, vol. 12, issue 2, pages 228-257 (previously circulated as: Segregation in Social Networks: A structural approach)
    + [Replication files](https://github.com/meleangelo/segnet)       
&nbsp;    
      

* [A structural model of dense network formation](files/bayesnet_march2016.pdf), May 2017, *Econometrica*, vol. 85, issue 3, pages 825-850 [(published version)](https://www.econometricsociety.org/publications/econometrica/2017/05/01/structural-model-dense-network-formation)
    + Online appendices: [A](files/bayesnet_march2016_appendixA.pdf) [B](files/bayesnet_march2016_appendixB.pdf) [C](files/bayesnet_march2016_appendixC.pdf) [D](files/bayesnet_march2016_appendixD.pdf) [E](files/bayesnet_march2016_appendixE.pdf)
    + [`netnew`](https://github.com/meleangelo/netnew): R package for replication
<!--    + Old versions: [November 2011](files/bayesnet_oct2011.pdf)  [July 2013](files/bayesnet_july2013.pdf) [March 2015](files/bayesnet_march2015.pdf)
    + [Old codes](files/bayesnet_replic.zip) for July 2013 version    -->
&nbsp;


* [Viral Altruism? Generosity and social contagion in online networks](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2441467), March 2016, *Sociological Science* (with [Mario Macis](https://sites.google.com/site/mmacis/) and [Nicola Lacetera](https://sites.google.com/site/nicolacetera/) )

* [Structural Models of Complementary Choices](files/ComplementaryChoices.pdf), *Marketing Letters*, 25, 3, pp: 245-256 Springer
(with Steve Berry, Ahmed Khwaja, Vineet Kumar, Andres Musalem, Ken Wilbur, Greg Allenby, Bharat Anand, Pradeep Chintagunta, Michael Hanemann, Przemek Jeziorski)
*Choice Symposium Invited Submission from* Marketing Letters

* [Poisson Indices of Segregation](files/pps_applied.pdf) (2013) *Regional Science and Urban Economics*  43, pages 65–85
    + [Example](files/webexample.zip): includes R code, R package, data for New York, readme files
    + Spatial Dissimilarity: [1990](files/sdism90_all.csv) [2000](files/sdism_all.csv) -- Spatial Exposure: [1990](files/sexp90_all.csv) [2000](sexp_all.csv) -- Spatial Fragmentation: [1990](files/sfrag90_all.csv)  [2000](files/sfrag_all.csv)


## Working papers,  submitted, revised
* [A Strategic Model of Software Dependency Networks](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4318082), (with Cornelius Fritz, [Co-Pierre Georg](https://cogeorg.github.io) and Michael Schweinberger)

* Latent Communities in Employment Relations and Wage Distributions: A Network Approach (with Lingxin Hao, Joshua Cape, Avanti Athreya, Cong Mu and Carey Priebe), Submitted

* [A structural model of business card exchange networks](https://arxiv.org/abs/2105.12704) (with Juan Nelson Martinez Dahbura, Takanori Nishida and Shota Komatsu), August 2021 *new version coming soon*
  + [lighthergm](https://github.com/sansan-inc/lighthergm): R library for scalable estimation of HERGMs    
&nbsp;


* [A structural model of firm collaborations with unobserved heterogeneity](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3267047), (with [Shweta Gaonkar](http://shwetagaonkar.com)), *new version coming soon*

* Creativity and Market Success: Evidence from the movie industry (with [Shweta Gaonkar](http://shwetagaonkar.com)), Reject and Resubmit at  *Strategic Entrepreneurship Journal*

## New and in progress

* Spectral estimation of a dynamic network formation model (with Avanti Athreya, Joshua Cape, Cong Mu, Lingxing Hao and Carey Priebe)
* A variational exchange algorithm for Bayesian estimation of ERGM models
* Microeconomic foundations of a latent position network model
* Network (video)games (with Micah Pollak and Phil Solimine)



## Old stuff
* Approximate Variational Inference for a Model of Social Interactions 

* [Racial Segregation and Public School Expenditure](files/LaFerraraMele.pdf) (with [Eliana La Ferrara](http://didattica.unibocconi.eu/mypage/index.php?IdUte=49273&cognome=LA%20FERRARA&nome=ELIANA&urlBackMy=) )

* [Who is afraid of the big bad wolf? Do pedophiles live closer to schools?](files/sexoff_paper.pdf) 

